
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("employees/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("employees", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit employees</h1>
</div>

<table align="center">
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->passwordField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="role_id">Role ID</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("role_id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fullname">Fullname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fullname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="job">Job</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("job", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contacts">Contacts</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("contacts", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Employee since</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("date", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Сохранить") ?></td>
    </tr>
</table>

</form>
