
<?php echo $this->getContent() ?>

<?php echo $this->tag->form("employees/create") ?>

<div align="center">
    <h1>Create employee</h1>
</div>

<table align="center">
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="role_id">Role Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("role_id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fullname">Fullname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fullname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="job">Job</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("job", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contacts">Contacts</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("contacts", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Date</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("date", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Сохранить") ?></td>
    </tr>
</table>

</form>

<table class="browse" align="center">
    <thead>
    <tr>
        <th>Id</th>
        <th>Username</th>
        <th>Fullname</th>
        <th>Role</th>
        <th>Job</th>
        <th>Contacts</th>
        <th>Moreinfo</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $user) { ?>
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->username ?></td>
            <td><?php echo $user->password ?></td>
            <td><?php echo $user->role_id ?></td>
            <td><?php echo $user->fullname ?></td>
            <td><?php echo $user->job ?></td>
            <td><?php echo $user->contacts ?></td>
            <td><?php echo $user->moreinfo ?></td>
            <td><?php echo $user->date ?></td>
            <td><?php echo $this->tag->linkTo(array("employees/edit/" . $user->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("employees/delete/" . $user->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
    <tr>
        <td colspan="2" align="right">
            <table align="center">
                <tr>
                    <td><?php echo $this->tag->linkTo("employees/search", "First") ?></td>
                    <td><?php echo $this->tag->linkTo("employees/search?page=" . $page->before, "Previous") ?></td>
                    <td><?php echo $this->tag->linkTo("employees/search?page=" . $page->next, "Next") ?></td>
                    <td><?php echo $this->tag->linkTo("employees/search?page=" . $page->last, "Last") ?></td>
                    <td><?php echo $page->current, "/", $page->total_pages ?></td>
                </tr>
            </table>
        </td>
    </tr>
    <tbody>
</table>
