
<?php echo $this->tag->form(array("/maintenance-schedule/create", 'class' => 'form-basic')); ?>


<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Maintenance Schedule</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Сохранить") ?></td>
    </tr>
</table>

</form>
