
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("carservices/new", "Create carservices")) ?>
</div>

<?php echo $this->tag->form(array("carservices/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search carservices</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="carservice">Carservice</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("carservice", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
