
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("users/new", "Create users")) ?>
</div>

<?php echo $this->tag->form(array("users/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search users</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fullname">Fullname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fullname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="role">Role</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("role", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="job">Job</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("job", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contacts">Contacts</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("contacts", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("date", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
