
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("clients/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("clients", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit clients</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="fullname">Fullname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fullname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contactemail">Contactemail</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("contactemail", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contactphone">Contactphone</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("contactphone", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="regdate">Regdate</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("regdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
