
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("clients/new", "Create clients")) ?>
</div>

<?php echo $this->tag->form(array("clients/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search clients</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fullname">Fullname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fullname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contactemail">Contactemail</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("contactemail", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contactphone">Contactphone</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("contactphone", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="regdate">Regdate</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("regdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
