
<?php echo $this->tag->form("/providedservices/create") ?>

<table class="basic-form" width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("providedservices", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Provided Services</h1>
</div>

<table class="basic-form">
    <tr>
        <td align="right">
            <label for="car_id">Car ID</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("car_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="work_id">Type of service</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("work_id", $services, "using" => array("id", "carservice"))); ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="master_id">Master who done work</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select(array("master_id", $employees, "using" => array("id", "fullname"))); ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cost">Total cost of service</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cost", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="startdate">Start date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("startdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="finishdate">Finish date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("finishdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="milage">Current Milage in km</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("milage", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="reminddate">Remind after date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("reminddate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="remindkm">Remind after km</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("remindkm", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Remind</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("remind", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Сохранить") ?></td>
    </tr>
</table>

</form>
