<?php use Phalcon\Tag; ?>
<div class="row">
    <div id="wrapper-login-form" class="large-3 large-centered columns">
            <h2>Please Login</h2>
        <?php echo $this->tag->form("/login"); ?>
            <p>
                <label for="username">Username</label>
                <?php echo Tag::textField("username") ?>
            </p>
            <p>
                <label for="password">Password</label>
        <?php echo Tag::passwordField("password") ?>
            </p>
        <p>
            <?php echo Tag::submitButton(array("Login", "class" => "button")) ?>
        </p>
        </form>
    </div>
</div>