
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("cars/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("cars", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit cars</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="regnum">Regnum</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("regnum", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="owner_id">Owner</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("owner_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="model">Model</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("model", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="bodynumber">Bodynumber</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("bodynumber", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="enginenumber">Enginenumber</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("enginenumber", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="regdate">Regdate</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("regdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="year">Year</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("year", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="milage">Milage</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("milage", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dailymilage">Dailymilage</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("dailymilage", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Сохранить") ?></td>
    </tr>
</table>

</form>
