
<?php echo $this->tag->form("cars/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("cars", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create cars</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="regnum">Regnum</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("regnum", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="owner">Owner</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("owner", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contactemail">Contactemail</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("contactemail", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="contactphones">Contactphones</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("contactphones", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="year">Year</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("year", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="milage">Milage</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("milage", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dailymilage">Dailymilage</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("dailymilage", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
