
<?php echo $this->tag->form("cars/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("cars", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create cars</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="regnum">Registration Number</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("regnum", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="owner_id">Owner ID</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("owner_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="model">Model</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("model", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="bodynumber">Bodynumber</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("bodynumber", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="enginenumber">Enginenumber</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("enginenumber", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="regdate">Registration date in Workshop</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("regdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="year">Year of the car in XXXX format</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("year", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="milage">Milage in km</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("milage", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dailymilage">Dailymilage in km</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("dailymilage", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="moreinfo">Moreinfo</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("moreinfo", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Сохранить") ?></td>
    </tr>
</table>

</form>
