<?php echo $this->getContent(); ?>
<div class="large-8 large-centered columns services-block">
    <h3>VIN <?php echo $car->vin; ?></h3>
    <table id="table-provided-services" align="center">
        <thead>
        <tr>
            <th>ID</th>
            <th width="85" data-tooltip class="has-tip prs-th" title="Номер Машины">#</th>
            <th width="100" data-tooltip class="has-tip prs-th" title="Дата проведения тех. обслуживания">Когда</th>
            <th data-tooltip class="has-tip prs-th" title="Тип технического облуживания">Tex. услуга</th>
            <th data-tooltip class="has-tip prs-th" title="Пробег машины в километрах на момент тех. обслуживания">Пробег</th>
            <th data-tooltip class="has-tip prs-th" title="Мастер выполнявший тех. обслуживани">Мастер</th>
            <th data-tooltip class="has-tip prs-th" title="Дополнительная информация">Заметка</th>
            <th data-tooltip class="has-tip prs-th" title="Напоминание о необходимости провести тех. осмотр после КМ">КМ</th>
            <th width="120" data-tooltip class="has-tip prs-th" title="Напоминание о необходимости провести тех. осмотр после Даты">Дата</th>
            <th class="remind-status-th prs-th">Статус напоминания</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $providedServices = $car->getProvidedServices(array(
            "order" => "startDate ASC",
            //"cache" => array("key" => "services-by-car-".$car->id, "lifetime" => 300),
        ));
            foreach ($providedServices as $providedService) {
                echo '<tr>';
                echo '<td>'.$providedService->id.'</td>';
                echo '<td>'.$car->regNumber.'</td>';
                echo '<td class="date-when">'.$providedService->startDate.'</td>';
                echo '<td>'.$carServices[$providedService->serviceId]['service'].'</td>';
                echo '<td>'.$providedService->milage.'</td>';
                echo '<td>'.$employees[$providedService->masterId]['fullname'].'</td>';
                echo '<td class="remind-status">'.$providedService->moreInfo.'</td>';
                //Get remind km status by current car
                echo '<td class="km-'.$providedService->getRemindKmStatus($car->milage, $car->dailyMilage, $car->milageDate).'">'.$providedService->getMilageRemind().'</td>';
                echo '<td class="date-'.$providedService->getRemindDateStatus().'">';
                echo $providedService->remindDate.'</td>';
                echo '<td class="remind-status">'.$providedService->remindStatus.'</td>';
                echo '</tr>';
            }
        ?>
        </tbody>
    </table>
</div>